# Generated by Django 5.0.7 on 2024-07-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        ("products", "0002_rename_price_product_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Бюджет на рекламу"
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название рекламной компании"
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="promoted_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="Рекламируемая услуга",
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="promotion_channel",
            field=models.CharField(max_length=255, verbose_name="Канал продвижения"),
        ),
    ]
