# Generated by Django 5.0.7 on 2024-07-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ads_budget_alter_ads_name_and_more"),
        ("products", "0003_alter_product_cost_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="promoted_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Рекламируемая услуга",
            ),
        ),
    ]
