# Generated by Django 5.0.7 on 2024-07-23 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_contract_alter_customer_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="activation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата активации клиента"
            ),
        ),
    ]
