# Generated by Django 5.0.7 on 2024-07-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="price",
            new_name="cost",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="date_from",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="date_to",
            new_name="start_date",
        ),
    ]
