# Generated by Django 5.0.7 on 2024-07-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_rename_price_contract_cost_and_more"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="customers.customer",
            ),
        ),
    ]
