# Generated by Django 5.0.7 on 2024-07-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="customer",
        ),
    ]
